/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolunkRouteImport } from './routes/rolunk'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as CsapatunkRouteImport } from './routes/csapatunk'
import { Route as BiztonsagRouteImport } from './routes/biztonsag'
import { Route as ArakRouteImport } from './routes/arak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SzolgaltatasokIndexRouteImport } from './routes/szolgaltatasok.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SzolgaltatasokNauiTanfolyamRouteImport } from './routes/szolgaltatasok.naui-tanfolyam'
import { Route as SzolgaltatasokSlugRouteImport } from './routes/szolgaltatasok.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolunkRoute = RolunkRouteImport.update({
  id: '/rolunk',
  path: '/rolunk',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CsapatunkRoute = CsapatunkRouteImport.update({
  id: '/csapatunk',
  path: '/csapatunk',
  getParentRoute: () => rootRouteImport,
} as any)
const BiztonsagRoute = BiztonsagRouteImport.update({
  id: '/biztonsag',
  path: '/biztonsag',
  getParentRoute: () => rootRouteImport,
} as any)
const ArakRoute = ArakRouteImport.update({
  id: '/arak',
  path: '/arak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokIndexRoute = SzolgaltatasokIndexRouteImport.update({
  id: '/szolgaltatasok/',
  path: '/szolgaltatasok/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokNauiTanfolyamRoute =
  SzolgaltatasokNauiTanfolyamRouteImport.update({
    id: '/szolgaltatasok/naui-tanfolyam',
    path: '/szolgaltatasok/naui-tanfolyam',
    getParentRoute: () => rootRouteImport,
  } as any)
const SzolgaltatasokSlugRoute = SzolgaltatasokSlugRouteImport.update({
  id: '/szolgaltatasok/$slug',
  path: '/szolgaltatasok/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arak': typeof ArakRoute
  '/biztonsag': typeof BiztonsagRoute
  '/csapatunk': typeof CsapatunkRoute
  '/galeria': typeof GaleriaRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolunk': typeof RolunkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/szolgaltatasok/$slug': typeof SzolgaltatasokSlugRoute
  '/szolgaltatasok/naui-tanfolyam': typeof SzolgaltatasokNauiTanfolyamRoute
  '/blog/': typeof BlogIndexRoute
  '/szolgaltatasok/': typeof SzolgaltatasokIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arak': typeof ArakRoute
  '/biztonsag': typeof BiztonsagRoute
  '/csapatunk': typeof CsapatunkRoute
  '/galeria': typeof GaleriaRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolunk': typeof RolunkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/szolgaltatasok/$slug': typeof SzolgaltatasokSlugRoute
  '/szolgaltatasok/naui-tanfolyam': typeof SzolgaltatasokNauiTanfolyamRoute
  '/blog': typeof BlogIndexRoute
  '/szolgaltatasok': typeof SzolgaltatasokIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arak': typeof ArakRoute
  '/biztonsag': typeof BiztonsagRoute
  '/csapatunk': typeof CsapatunkRoute
  '/galeria': typeof GaleriaRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolunk': typeof RolunkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/szolgaltatasok/$slug': typeof SzolgaltatasokSlugRoute
  '/szolgaltatasok/naui-tanfolyam': typeof SzolgaltatasokNauiTanfolyamRoute
  '/blog/': typeof BlogIndexRoute
  '/szolgaltatasok/': typeof SzolgaltatasokIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arak'
    | '/biztonsag'
    | '/csapatunk'
    | '/galeria'
    | '/kapcsolat'
    | '/rolunk'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/szolgaltatasok/$slug'
    | '/szolgaltatasok/naui-tanfolyam'
    | '/blog/'
    | '/szolgaltatasok/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arak'
    | '/biztonsag'
    | '/csapatunk'
    | '/galeria'
    | '/kapcsolat'
    | '/rolunk'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/szolgaltatasok/$slug'
    | '/szolgaltatasok/naui-tanfolyam'
    | '/blog'
    | '/szolgaltatasok'
  id:
    | '__root__'
    | '/'
    | '/arak'
    | '/biztonsag'
    | '/csapatunk'
    | '/galeria'
    | '/kapcsolat'
    | '/rolunk'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/szolgaltatasok/$slug'
    | '/szolgaltatasok/naui-tanfolyam'
    | '/blog/'
    | '/szolgaltatasok/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArakRoute: typeof ArakRoute
  BiztonsagRoute: typeof BiztonsagRoute
  CsapatunkRoute: typeof CsapatunkRoute
  GaleriaRoute: typeof GaleriaRoute
  KapcsolatRoute: typeof KapcsolatRoute
  RolunkRoute: typeof RolunkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SzolgaltatasokSlugRoute: typeof SzolgaltatasokSlugRoute
  SzolgaltatasokNauiTanfolyamRoute: typeof SzolgaltatasokNauiTanfolyamRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SzolgaltatasokIndexRoute: typeof SzolgaltatasokIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolunk': {
      id: '/rolunk'
      path: '/rolunk'
      fullPath: '/rolunk'
      preLoaderRoute: typeof RolunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csapatunk': {
      id: '/csapatunk'
      path: '/csapatunk'
      fullPath: '/csapatunk'
      preLoaderRoute: typeof CsapatunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biztonsag': {
      id: '/biztonsag'
      path: '/biztonsag'
      fullPath: '/biztonsag'
      preLoaderRoute: typeof BiztonsagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arak': {
      id: '/arak'
      path: '/arak'
      fullPath: '/arak'
      preLoaderRoute: typeof ArakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok/': {
      id: '/szolgaltatasok/'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok/'
      preLoaderRoute: typeof SzolgaltatasokIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok/naui-tanfolyam': {
      id: '/szolgaltatasok/naui-tanfolyam'
      path: '/szolgaltatasok/naui-tanfolyam'
      fullPath: '/szolgaltatasok/naui-tanfolyam'
      preLoaderRoute: typeof SzolgaltatasokNauiTanfolyamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok/$slug': {
      id: '/szolgaltatasok/$slug'
      path: '/szolgaltatasok/$slug'
      fullPath: '/szolgaltatasok/$slug'
      preLoaderRoute: typeof SzolgaltatasokSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArakRoute: ArakRoute,
  BiztonsagRoute: BiztonsagRoute,
  CsapatunkRoute: CsapatunkRoute,
  GaleriaRoute: GaleriaRoute,
  KapcsolatRoute: KapcsolatRoute,
  RolunkRoute: RolunkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  SzolgaltatasokSlugRoute: SzolgaltatasokSlugRoute,
  SzolgaltatasokNauiTanfolyamRoute: SzolgaltatasokNauiTanfolyamRoute,
  BlogIndexRoute: BlogIndexRoute,
  SzolgaltatasokIndexRoute: SzolgaltatasokIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
